title: [Apuntes Clase]
description: [Curso 2024-25 - IES El Rincón]
show_downloads: ["True"]
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-readme-index